server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    preferIpAddress: true

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: STUDENT-SERVICE
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/api_student/**

        - id: COURSE-SERVICE
          uri: lb://COURSE-SERVICE
          predicates:
              - Path=/api_course/**








